### ISSUE TITLE
Necrobot updated

### ISSUE THREAD

**Issue by bt3new** [disdain13/PokeRoadie#23]
just in case you missed it :)
https://github.com/NECROBOTIO/NecroBot

**Comment by disdain13** [comment]
No, I didn't miss it. But, I have been struggling to get it integrated since FeroxRev has not released an updated C# port API. I am currently trying to move the changes in manually based on the Necro bot changes.

**Comment by disdain13** [comment]
I spent all night trying to port over several different implementations which appear to be working. Necro, Spegeli, and a raw implementation from FeroxRev tickets 125-128. I have eveything compiling, but when I run it, after initial login, it complains about a missing pointer to encrypt in encrypt.dll. I am still trying to resolve this issue.

**Comment by disdain13** [comment]
I did get the encrypt.dll c++ project, compiled it, and moved it into the bin dir. I thought that would be all it needed.

**Comment by disdain13** [comment]
I have committed changes which have resolved the pokestop issue. You will notice there are a couple encounter issues happening. This is from the new LURE and INCENSE capture. I will have those fixed shortly. It is nice to be working again!

**Comment by disdain13** [comment]
I will be doing a compiled release tonight

**Comment by RiC0MD** [comment]
Great work!

**Comment by disdain13** [comment]
Thanks man. I fumbled a bit trying to piece together in installation that would actually run. I could get all 3 to compile, but getting the signature to actually work took a little bit more. I was lucky enough to find a decent C# port of the encrypt.dll, which was causing me the issues.

**Comment by RiC0MD** [comment]
Ran into one issue, sadly was running it outside of VS, Unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PokeRoadie.Utils.ApiFailureStrategy.<DoLogin>d__6.MoveNext() in C:\XXXXX\PokeRoadie\PokeRoadie\Utils\ApiFailureStrategy.c
s:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__5(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

Ill see if I can trace it down here in a bit here this afternoon if you haven't found it by then.

**Comment by disdain13** [comment]
I am looking into it. This is code recently introduced to handle Request/Response failures with the Pokemon Servers. This kind of failure generally happens when calls are made too quickly. I am actually not liking the IApiFailureStrategy implementation of FeroxRev's because it depends on it failing. In my previous implementation (before this new strategy), I had a delay timer calculating the amount of time since the last request, and offsetting the delay as needed. I found running requests at about 350ms apart, it would run smoothly. I did not put a hard Delay(350) call. I saved the time of the last request, subtracted the time passed from the current time, and if it was less than 350, delay as needed. It worked wonderfully. Then I tried this new thing they did, and so far I am not happy. It will just try to send the requests, then when one fails, it waits 500ms. Not the biggest deal, but at some point Niantic will catch on, and bots trying to "force" requests will be dealt with. I am probably going to rewrite the HttpClientExtensions class back to the way I had it.

**Comment by disdain13** [comment]
OK, I rewrote the ApiFailureStrategy and added back the min request delay.

**Comment by RiC0MD** [comment]
Was just starting to dig into but looks like you beat me :) :+1:

**Comment by RiC0MD** [comment]
So it was working for while, but now I'm just getting
[18:18:27](ERROR) (FATAL ERROR) Unhandled exception encountered: Object reference not set to an instance of an object..
[18:18:27](ATTENTION) Restarting the application due to error...
[18:18:28](INFO) Logging in via: Google
[18:18:28](INFO) Client logged in
[18:18:32](ERROR) (FATAL ERROR) Unhandled exception encountered: Object reference not set to an instance of an object..
[18:18:32](ATTENTION) Restarting the application due to error...
[18:18:32](INFO) Logging in via: Google
[18:18:33](INFO) Client logged in
[18:18:37](ERROR) (FATAL ERROR) Unhandled exception encountered: Object reference not set to an instance of an object..
[18:18:37](ATTENTION) Restarting the application due to error...
[18:18:37](INFO) Logging in via: Google
[18:18:38](INFO) Client logged in
[18:18:41](ERROR) (FATAL ERROR) Unhandled exception encountered: Object reference not set to an instance of an object..
[18:18:41](ATTENTION) Restarting the application due to error...
[18:18:42](INFO) Logging in via: Google
[18:18:42](INFO) Client logged in
[18:18:46](ERROR) (FATAL ERROR) Unhandled exception encountered: Object reference not set to an instance of an object..
[18:18:46](ATTENTION) Restarting the application due to error...
[18:18:46](INFO) Logging in via: Google
[18:18:47](INFO) Client logged in
[18:18:50](ERROR) (FATAL ERROR) Unhandled exception encountered: Object reference not set to an instance of an object..
[18:18:50](ATTENTION) Restarting the application due to error...
[18:18:50](INFO) Logging in via: Google
[18:18:51](INFO) Client logged in

Haven't been able to trace down where its coming from just yet though.

**Comment by RiC0MD** [comment]
Just noticed seems PGO is down right now for the past 20mins, so probably not code related.

**Comment by disdain13** [comment]
Yeah, I am gonna run it and try to handle the exception at least. That way in the future, it has a little better message.

**Comment by disdain13** [comment]
I must have missed the window, I am running it and have not hit exception yet.

**Comment by disdain13** [comment]
However, I am getting 0 catches, with no error. Seems like they changed something else...

**Comment by disdain13** [comment]
I am stepping through the code now.

**Comment by disdain13** [comment]
Nope, this is my bad. My pokemon inventory is full and it is not reporting it properly. Fixing it now.

**Comment by disdain13** [comment]
Fixed.
