### ISSUE TITLE
Unhandled exceptions

### ISSUE THREAD

**Issue by RiC0MD** [disdain13/PokeRoadie#26]
Everything was working well for awhile, but endless loop of exceptions again

[21:55:26](INFO) Logging in via: Google
[21:55:27](INFO) Client logged in
[21:55:29](ERROR) Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at PokeRoadie.Statistics.GetUsername(Client client, GetPlayerResponse profile) in C:\Source\Pokemon\PokeRoadie\PokeRoadie\Utils\Statistics.cs:line 60
   at PokeRoadie.PokeRoadieLogic.<WriteStats>d__112.MoveNext() in C:\Source\Pokemon\PokeRoadie\PokeRoadie\PokeRoadieLogic.cs:line 217
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokeRoadie.PokeRoadieLogic.<PostLoginExecute>d__117.MoveNext() in C:\Source\Pokemon\PokeRoadie\PokeRoadie\PokeRoadieLogic.cs:line 536
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokeRoadie.PokeRoadieLogic.<Execute>d__116.MoveNext() in C:\Source\Pokemon\PokeRoadie\PokeRoadie\PokeRoadieLogic.cs:line 475
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at PokeRoadie.Program.<>c.<Main>b__3_1() in C:\Source\Pokemon\PokeRoadie\PokeRoadie\Program.cs:line 64
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at PokeRoadie.Statistics.GetUsername(Client client, GetPlayerResponse profile) in C:\Source\Pokemon\PokeRoadie\PokeRoadie\Utils\Statistics.cs:line 60
   at PokeRoadie.PokeRoadieLogic.<WriteStats>d__112.MoveNext() in C:\Source\Pokemon\PokeRoadie\PokeRoadie\PokeRoadieLogic.cs:line 217
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokeRoadie.PokeRoadieLogic.<PostLoginExecute>d__117.MoveNext() in C:\Source\Pokemon\PokeRoadie\PokeRoadie\PokeRoadieLogic.cs:line 536
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokeRoadie.PokeRoadieLogic.<Execute>d__116.MoveNext() in C:\Source\Pokemon\PokeRoadie\PokeRoadie\PokeRoadieLogic.cs:line 475<---

[21:55:29](INFO) Logging in via: Google
[21:55:30](INFO) Client logged in

Haven't had much time to dig into it yet, starting now.

**Comment by disdain13** [comment]
Yeah, I think it still may be server related. I run for like 10 minutes, then I hit a series of errors. It hangs up for awhile, then it resets and starts working again.

**Comment by disdain13** [comment]
I just pushed some attempts at trying to handle the object ref exceptions.

**Comment by RiC0MD** [comment]
Been running for about 20mins now, and so far so good.  Going to through the code up to the colo server to run over night, will report back if any issues come morning.  Thanks again for all the work.

**Comment by disdain13** [comment]
no problem, let me know how it goes. 8)

**Comment by RiC0MD** [comment]
Made it for a couple hours, adjusted my transfer/evolve settings a bit to keep only the tops as my account was quickly filling up with lowbies, and then it started again:
[00:42:33](INFO) Found 32 Pokestops | 5 Gyms
[00:42:33](FATAL ERROR) Unhandled exception encountered: Nullable object must have a value..
[00:42:33](ATTENTION) Restarting the application due to error...
[00:42:34](INFO) Logging in via: Google
[00:42:34](INFO) Client logged in
[00:42:34](ATTENTION) No usable PokeStops found in your area.
[00:42:39](INFO) Found 32 Pokestops | 5 Gyms
[00:42:40](FATAL ERROR) Unhandled exception encountered: Nullable object must have a value..
[00:42:40](ATTENTION) Restarting the application due to error...
[00:42:40](INFO) Logging in via: Google
[00:42:41](INFO) Client logged in
[00:42:41](ATTENTION) No usable PokeStops found in your area.
[00:42:46](INFO) Found 32 Pokestops | 5 Gyms
[00:42:46](FATAL ERROR) Unhandled exception encountered: Nullable object must have a value..
[00:42:46](ATTENTION) Restarting the application due to error...
[00:42:46](INFO) Logging in via: Google
[00:42:47](INFO) Client logged in
[00:42:47](ATTENTION) No usable PokeStops found in your area.
[00:42:52](INFO) Found 32 Pokestops | 5 Gyms
[00:42:53](FATAL ERROR) Unhandled exception encountered: Nullable object must have a value..
[00:42:53](ATTENTION) Restarting the application due to error...
[00:42:53](INFO) Logging in via: Google
[00:42:53](INFO) Client logged in
[00:42:53](ATTENTION) No usable PokeStops found in your area.

This is also commit 67ad46f8 (latest as of posting), I was using the previous commit before trying to update as well.

Stack trace:
[00:46:07](ERROR) Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Nullable`1.get_Value()
   at PokeRoadie.PokeRoadieLogic.<ProcessNearby>d__124.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokeRoadie.PokeRoadieLogic.<CatchNearbyPokemons>d__151.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokeRoadie.PokeRoadieLogic.<ProcessPokeStop>d__127.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokeRoadie.PokeRoadieLogic.<ProcessFortList>d__125.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokeRoadie.PokeRoadieLogic.<ExecuteFarming>d__122.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokeRoadie.PokeRoadieLogic.<ExecuteFarming>d__121.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokeRoadie.PokeRoadieLogic.<PostLoginExecute>d__120.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokeRoadie.PokeRoadieLogic.<Execute>d__119.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at PokeRoadie.Program.<>c.<Main>b__3_1()
---> (Inner Exception #0) System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Nullable`1.get_Value()
   at PokeRoadie.PokeRoadieLogic.<ProcessNearby>d__124.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokeRoadie.PokeRoadieLogic.<CatchNearbyPokemons>d__151.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokeRoadie.PokeRoadieLogic.<ProcessPokeStop>d__127.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokeRoadie.PokeRoadieLogic.<ProcessFortList>d__125.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokeRoadie.PokeRoadieLogic.<ExecuteFarming>d__122.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokeRoadie.PokeRoadieLogic.<ExecuteFarming>d__121.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokeRoadie.PokeRoadieLogic.<PostLoginExecute>d__120.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokeRoadie.PokeRoadieLogic.<Execute>d__119.MoveNext()<---

**Comment by RiC0MD** [comment]
Still seem to be having the problem with the latest commits this morning:
[09:36:55](INFO) Found 32 Pokestops | 5 Gyms
[09:36:56](FATAL ERROR) Unhandled exception encountered: Nullable object must have a value..
[09:36:56](ATTENTION) Restarting the application due to error...
[09:36:56](INFO) Logging in via: Google
[09:36:56](INFO) Client logged in
[09:36:56](ATTENTION) No usable PokeStops found in your area.
[09:37:01](ATTENTION) No usable PokeStops found in your area.
[09:37:07](INFO) Found 32 Pokestops | 5 Gyms
[09:37:07](FATAL ERROR) Unhandled exception encountered: Nullable object must have a value..
[09:37:07](ATTENTION) Restarting the application due to error...
[09:37:07](INFO) Logging in via: Google
[09:37:08](INFO) Client logged in
[09:37:08](ATTENTION) No usable PokeStops found in your area.
[09:37:13](INFO) Found 32 Pokestops | 5 Gyms
[09:37:14](FATAL ERROR) Unhandled exception encountered: Nullable object must have a value..
[09:37:14](ATTENTION) Restarting the application due to error...

**Comment by disdain13** [comment]
I will be looking into it in an hour or so, it is a busy day at work today...8)

**Comment by disdain13** [comment]
Sorry, man work was chaos, I am just getting into it now.

**Comment by RiC0MD** [comment]
Just tried the latest pull, still getting
[22:10:15](ERROR) Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Nullable`1.get_Value()
   at PokeRoadie.PokeRoadieLogic.<ProcessNearby>d__125.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

Starting to wonder if it has to do with the area I'm in specifically, so if you want to try it to reproduce it, my coords are
<CurrentLatitude>45.030476981956063</CurrentLatitude>
  <CurrentLongitude>-93.287779878376469</CurrentLongitude>
  <CurrentAltitude>10</CurrentAltitude>

Which is a pretty awesome spot in central MN (not my actual location)

**Comment by RiC0MD** [comment]
So one thing I noticed to the above, looks like PokeRoadieInventory.cs, line 494, was returning a null _cachedInventory;
Adding a check here though just seemed to push the issue further down the chain, don't have my head very well wrapped around the code base, so easily could be missing something.

**Comment by disdain13** [comment]
I made a bunch of fixes last night, but I did hit the error after about 30-45 mins. Could you please post your settings file, minus user/pass of course. It may be feature specific. Thanks

**Comment by Hanshagbard** [comment]
I also get this error, but i hit it directly after the bot starts.

```
  <DestinationsEnabled>false</DestinationsEnabled>
  <MinutesPerDestination>30</MinutesPerDestination>
  <DestinationIndex>0</DestinationIndex>
  <CurrentLatitude>60.673017</CurrentLatitude>
  <CurrentLongitude>17.146347</CurrentLongitude>
  <CurrentAltitude>10</CurrentAltitude>
  <MinSpeed>8</MinSpeed>
  <MaxSpeed>50</MaxSpeed>
  <MaxDistance>5000</MaxDistance>
  <MaxDistanceForLongTravel>65</MaxDistanceForLongTravel>
  <EnableSpeedAdjustment>true</EnableSpeedAdjustment>
  <EnableSpeedRandomizer>true</EnableSpeedRandomizer>
  <MaxSecondsBetweenStops>30</MaxSecondsBetweenStops>
  <FlyingEnabled>false</FlyingEnabled>
  <FlyLikeCaptKirk>false</FlyLikeCaptKirk>
  <FlyingSpeed>250</FlyingSpeed>
  <PingStopsWhileFlying>false</PingStopsWhileFlying>
  <UseGPXPathing>false</UseGPXPathing>
  <GPXFile>GPXFILE.gpx</GPXFile>
  <EvolvePokemon>true</EvolvePokemon>
  <EvolvePriorityType>V</EvolvePriorityType>
  <EvolveAboveIV>0</EvolveAboveIV>
  <EvolveAboveV>300</EvolveAboveV>
  <EvolveAboveCp>0</EvolveAboveCp>
  <UsePokemonsToEvolveList>false</UsePokemonsToEvolveList>
  <TransferPokemon>true</TransferPokemon>
  <TransferPriorityType>V</TransferPriorityType>
  <KeepDuplicateAmount>2</KeepDuplicateAmount>
  <KeepAboveIV>0</KeepAboveIV>
  <KeepAboveV>300</KeepAboveV>
  <KeepAboveCp>1700</KeepAboveCp>
  <TransferBelowIV>0</TransferBelowIV>
  <TransferBelowV>0</TransferBelowV>
  <TransferBelowCp>0</TransferBelowCp>
  <TransferTrimFatCount>0</TransferTrimFatCount>
  <NotTransferPokemonsThatCanEvolve>false</NotTransferPokemonsThatCanEvolve>
  <PowerUpPokemon>true</PowerUpPokemon>
  <PowerUpPriorityType>V</PowerUpPriorityType>
  <PowerUpAboveIV>0</PowerUpAboveIV>
  <PowerUpAboveV>350</PowerUpAboveV>
  <PowerUpAboveCp>2000</PowerUpAboveCp>
  <MinStarDustForPowerUps>150000</MinStarDustForPowerUps>
  <UsePokemonsToPowerUpList>false</UsePokemonsToPowerUpList>
  <MinCandyForPowerUps>150</MinCandyForPowerUps>
  <MaxPowerUpsPerRound>3</MaxPowerUpsPerRound>
  <CatchPokemon>true</CatchPokemon>
  <VisitPokestops>true</VisitPokestops>
  <MoveWhenNoStops>false</MoveWhenNoStops>
  <PrioritizeStopsWithLures>false</PrioritizeStopsWithLures>
  <LoiteringActive>false</LoiteringActive>
  <VisitGyms>true</VisitGyms>
  <AutoDeployAtTeamGyms>true</AutoDeployAtTeamGyms>
  <PokeBallBalancing>true</PokeBallBalancing>
  <UseLuckyEggs>true</UseLuckyEggs>
  <UseIncense>true</UseIncense>
  <UseRevives>true</UseRevives>
  <UsePotions>true</UsePotions>
  <UseEggIncubators>true</UseEggIncubators>
  <UsePokemonToNotCatchList>false</UsePokemonToNotCatchList>
  <DisplayRefreshMinutes>10</DisplayRefreshMinutes>
  <DisplayAggregateLog>false</DisplayAggregateLog>
  <DisplayAllPokemonInLog>false</DisplayAllPokemonInLog>
  <WaitOnStart>false</WaitOnStart>
  <WaypointLatitude>60.673017</WaypointLatitude>
  <WaypointLongitude>17.146347</WaypointLongitude>
  <WaypointAltitude>9</WaypointAltitude>
  <UseProxy>false</UseProxy>
  <UseProxyHost />
  <UseProxyPort />
  <UseProxyAuthentication>false</UseProxyAuthentication>
  <UseProxyUsername />
  <UseProxyPassword />
</PokeRoadieSettings>
```

**Comment by disdain13** [comment]
@RiC0MD & @Hanshagbard - Could you pull the latest source and try again. Also be sure "UseIncense" is turned off. It is causing errors, I am looking into it now. Let me know your results. If you need me to do a compiled release, let me know.

**Comment by disdain13** [comment]
I looked at a few other bots, they are just ignoring all exceptions from the getCachedInventory call now. I made PokeRoadie do the same.

**Comment by disdain13** [comment]
I believe the nullable exception is due to UseIncense though.

**Comment by disdain13** [comment]
@RiC0MD - Thanks for your help for the past few days. You have really been helping me test out some of these issues/features. You have been invited to be a contributor 8)

**Comment by RiC0MD** [comment]
@disdain13 So here's what's interesting, left my config totally as is, pulled latest commit, and it seems like its working.  I do have UseIncense still on at this point.  Ill keep testing as is, until / if I get nullable again, and disable it at that point.  Also thanks for the invite!

**Comment by Hanshagbard** [comment]
The latest commit removed the error for me aswell, and have now worked for 5 minutes.

**Comment by disdain13** [comment]
Excellent, let me know if you hit something.

**Comment by RiC0MD** [comment]
Well been running for couple hours now, saw 1 caught exception, and nothing uncaught at this point.  Will report back if that changes, but thus far looking really good!
