### ISSUE TITLE
Error at start up

### ISSUE THREAD

**Issue by dechen1211** [disdain13/PokeRoadie#61]
This is an error i got when i start the bot.  Please help!!

[10:12:07](ERROR) Could not save C:\Users\Dech\Downloads\pb\PR 8.19\Temp\Session.xml. Error: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Dech\Downloads\pb\PR 8.19\Temp\Session.xml'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at PokeRoadie.PokeRoadieSettings.SaveSession(SessionData session) in C:\Users\Matt\Source\Repos\PokeRoadie\PokeRoadie\PokeRoadieSettings.cs:line 621
[10:12:07](ERROR) CurrentLatitude and CurrentLongitude not set in the Configs/Settings.xml. Application will exit in 15 seconds...

Anyhelp would be appreciated.  Thanks in advance.

**Comment by flavery79** [comment]
Getting same error message on startup:

[10:05:49](ERROR) Could not save C:\Users\myusername\Desktop\New\Temp\Session.xml. Error: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\myusername\Desktop\New\Temp\Session.xml'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at PokeRoadie.PokeRoadieSettings.SaveSession(SessionData session) in C:\Users\Matt\Source\Repos\PokeRoadie\PokeRoadie\PokeRoadieSettings.cs:line 621
[10:05:49](ERROR) CurrentLatitude and CurrentLongitude not set in the Configs/Settings.xml. Application will exit in 15 seconds...

**Comment by dechen1211** [comment]
Flavery79, just put down lat & long on the settings.xml.  It should be good to use

**Comment by disdain13** [comment]
Note: This is just because I was not checking if the "Temp" directory existed. If you create a "Temp" directory in the primary application folder, this should resolve the issue. I have put code in to check/create this directory on start, it is checked in, will be in tonight's release.
